---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 8/6/19 9:57 AM
---
---

local typedefs = require("kong.db.schema.typedefs")

return {
    name = "test",
    fields = {
        --{
        --    protocols = {typedefs.protocols_http, typedefs.protocols}
        --},
        {
            config = {
                type = "record",
                fields = {
                    {
                        key = {
                            type = "string",
                            default = "123"
                        }
                    },
                    {
                        header = {
                            type = "string",
                            default = "TOKEN",
                        }
                    },
                    {
                        method = {
                            type = "string",
                            default = "GET"
                        }
                    }
                }
            }
        },
        {
            consumer = typedefs.no_consumer
        }
    }
}

