---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 7/23/19 9:27 AM
---
--require("mobdebug").start()

local endpoints = require "kong.api.endpoints"

local credentials_schema = kong.db.tdt_credentials.schema

-- local HTTP_NOT_FOUND = 404

local function doGet()
    print("...doGet....")
    ngx.log(ngx.ERR, "============ Bye World! ============")
    return "hello lua!"
end

return {

    ["/tdt-auths"] = {
        schema = credentials_schema,
        methods = {
            GET = endpoints.get_collection_endpoint(credentials_schema)
            --GET = doGet()
        }
    }
}