---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 7/23/19 9:27 AM
---

local typedefs = require "kong.db.schema.typedefs"


return {
    -- this plugin only results in one custom DAO, named `keyauth_credentials`:
    tdt_credentials = {
        name               = "tdt_credentials", -- the actual table in the database
        endpoint_key       = "key",
        primary_key        = { "id" },
        cache_key          = { "key" },
        generate_admin_api = true,
        fields = {
            {
                -- a value to be inserted by the DAO itself
                -- (think of serial id and the uniqueness of such required here)
                id = typedefs.uuid,
            },
            {
                -- also interted by the DAO itself
                -- created_at = typedefs.auto_timestamp_s,
                name = {
                    type    = "string",
                    unique  = true
                }
            },
            {
                -- a unique API key
                key = {
                    type      = "string",
                    required  = false,
                    unique    = true
                },
            },
        },
    },
}