---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by root.
--- DateTime: 7/23/19 10:32 AM
---

return {
    postgres = {
        up = [[
      CREATE TABLE IF NOT EXISTS tdt_credentials(
        "id"     uuid          PRIMARY KEY,
        "name"   text          UNIQUE,
        "key"    TEXT          UNIQUE
      );

    ]],
    },

    cassandra = {
        up = [[
    ]],
    },
}